# ApexPlanet Internship : Telco Churn dataset analysis 
# Task 2 :
#         SQL for data extraction and analysis

In [36]:
import pandas as pd
from sqlalchemy import create_engine

In [39]:
from Task2_database_utility import get_database_engine

In [40]:
engine = get_database_engine()

# Python + SQLite Integration

This notebook demonstrates how Python can connect to a SQLite database, execute SQL queries, and retrieve results as Pandas DataFrames.

In [41]:
engine = create_engine("sqlite:///F:\\New folder\\SQL\\SQL_Telco_Churn.db")

In [44]:
from sqlalchemy import inspect
inspector = inspect(engine)
inspector.get_table_names()

['contract_info', 'customers']

## Query 

Retrieve all customer records from the database.

In [43]:
query = """
SELECT *
FROM customers
"""
df = pd.read_sql(query, engine)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

## Business Questions 
This section contains 10 business questions that are answered using SQL

## Business Question 1

How many customers are present in the dataset?

In [23]:
query = """
SELECT COUNT(*) AS total_customers
FROM customers
"""
result = pd.read_sql(query, engine)
result

   total_customers
0             7032

## Business Question 2

How many customers have churned?

In [25]:
query = """
SELECT COUNT(*) AS churned_customers
FROM customers
WHERE Churn = 'Yes'
"""
result = pd.read_sql(query, engine)
result

   churned_customers
0               1869

## Business Question 3

What is the average monthly charge?

In [26]:
query = """
SELECT AVG(MonthlyCharges) AS average_monthly_charge
FROM customers
"""
result = pd.read_sql(query, engine)
result

   average_monthly_charge
0               64.798208

## Business Question 4

How many customers are there in each contract type?

In [27]:
query = """
SELECT Contract,
       COUNT(*) AS customer_count
FROM customers
GROUP BY Contract
"""
result = pd.read_sql(query, engine)
result

         Contract  customer_count
0  Month-to-month            3875
1        One year            1472
2        Two year            1685

## Business Question 5

Which contract type has the highest number of churned customers?

In [28]:
query = """
SELECT Contract,
       COUNT(*) AS churned_customers
FROM customers
WHERE Churn = 'Yes'
GROUP BY Contract
ORDER BY churned_customers DESC
"""
result = pd.read_sql(query, engine)
result

         Contract  churned_customers
0  Month-to-month               1655
1        One year                166
2        Two year                 48

## Business Question 6

What is the average tenure of customers?

In [29]:
query = """
SELECT AVG(tenure) AS average_tenure
FROM customers
"""
result = pd.read_sql(query, engine)
result

   average_tenure
0       32.421786

## Business Question 7

Which internet service is used by the most customers?

In [30]:
query = """
SELECT InternetService,
       COUNT(*) AS customer_count
FROM customers
GROUP BY InternetService
ORDER BY customer_count DESC
"""
result = pd.read_sql(query, engine)
result

  InternetService  customer_count
0     Fiber optic            3096
1             DSL            2416
2              No            1520

## Business Question 8

Which payment method is most commonly used?

In [32]:
query = """
SELECT PaymentMethod,
       COUNT(*) AS customer_count
FROM customers
GROUP BY PaymentMethod
ORDER BY customer_count DESC
"""
result = pd.read_sql(query, engine)
result

               PaymentMethod  customer_count
0           Electronic check            2365
1               Mailed check            1604
2  Bank transfer (automatic)            1542
3    Credit card (automatic)            1521

## Business Question 9

Which customers pay more than the average monthly charge?

In [33]:
query = """
SELECT customerID,
       MonthlyCharges
FROM customers
WHERE MonthlyCharges >
(
    SELECT AVG(MonthlyCharges)
    FROM customers
)
ORDER BY MonthlyCharges DESC
"""
result = pd.read_sql(query, engine)
result.head(10)

   customerID  MonthlyCharges
0  7569-NMZYQ          118.75
1  8984-HPEMB          118.65
2  5989-AXPUC          118.60
3  5734-EJKXG          118.60
4  8199-ZLLSA          118.35
5  9924-JPRMC          118.20
6  2889-FPWRM          117.80
7  3810-DVDQQ          117.60
8  9739-JLPQJ          117.50
9  2302-ANTDP          117.45

## Business Question 10

What is the ranking of customers based on monthly charges?

In [35]:
query = """
SELECT
    customerID,
    MonthlyCharges,
    RANK() OVER (
        ORDER BY MonthlyCharges DESC
    ) AS charge_rank
FROM customers
"""
result = pd.read_sql(query, engine)
result.head(10)

   customerID  MonthlyCharges  charge_rank
0  7569-NMZYQ          118.75            1
1  8984-HPEMB          118.65            2
2  5989-AXPUC          118.60            3
3  5734-EJKXG          118.60            3
4  8199-ZLLSA          118.35            5
5  9924-JPRMC          118.20            6
6  2889-FPWRM          117.80            7
7  3810-DVDQQ          117.60            8
8  9739-JLPQJ          117.50            9
9  2302-ANTDP          117.45           10